version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     networks:
       - net
     deploy:
       replicas: 1
       resources:
         reservations:
           cpus: '0.2'
           memory: 32M
         limits:
           cpus: "0.5"
           memory: 512M
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     image: wordpress:latest
     networks:
       - net
       - webproxy
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     deploy:
       replicas: 1
       resources:
         reservations:
           cpus: '0.2'
           memory: 32M
         limits:
           cpus: "1.6"
           memory: 1G
       labels:
        - traefik.enable=true
        - traefik.docker.network=webproxy
        - traefik.http.routers.${APPNAME}-https.rule=Host(`${APPNAME}.${DOMAIN}`)
        - traefik.http.routers.${APPNAME}-https.entrypoints=websecure
        - traefik.http.routers.${APPNAME}-https.tls.certresolver=default
        - traefik.http.services.${APPNAME}.loadbalancer.server.port=80
volumes:
    db_data:

networks:
  net:
  webproxy:
    external: true